---
title: "About"
---

About this site

```{r}
1 + 1
```

Dips

Snow Bunting (Out Head, 2nd Jan)

Eurasian Goshawk (North Haugh Meadow, 7th Feb)

\*Eurasian Goshawk (Bogward Rd, 21st Feb)

\*Brambling (Bogward Rd, 21st Feb)

Snow Bunting (West Sands, 23rd Feb)

\*White-fronted Goose (Bogward Rd, 26th Feb)

Snow Bunting (Out Head, 1st Mar)

Snow Bunting (Out Head, 2nd Mar)

Snow Bunting (Out Head, 11th Mar)

Snow Bunting (Out Head, 26th Mar)

\*Hawfinch (Bogward Rd, 4th Apr)

\*Brambling (Bogward Rd, 4th Apr)

\*Red Crossbill (Bogward Rd, 4th Apr)

\*Merlin (Spinkie Den, 7th Apr)

\*Ring Ouzel (Bogward Rd, 13th Apr)

\*Brambling (Bogward Rd, 13th Apr)

\*Tree Pipit (Bogward Rd, 20th Apr)

\*Arctic Loon (Out Head, 22nd Apr)

Lesser Whitethroat (Out Head, 1st May)

\*Common Grasshopper Warbler (Out Head, 1st May)

\*Common Grasshopper Warbler (Out Head, 7th May)

\*Nuthatch (Bogward Rd, 12th May)

\*Lesser Whitethroat (Bogward Rd, 3rd Jun)

\*Arctic Loon (Out Head, 7th Jul)

\*Arctic Loon (The Scores, 8th Jul)

\*Tree Pipit (Bogward Rd, 15th Jul)

Little Tern (Out Head, 19th Jul)

Western Marsh Harrier (Farms between A917 and Grange Rd, 10th Aug)

\*Pomarine Jaeger (Out Head, 11th Aug)

\*Black Tern (Out Head, 11th Aug)

\*Mediterranean Gull (Out Head, 11th Aug)

\*Black Tern (Out Head, 14th Aug)

\*Whinchat (Out Head, 14th Aug)

\*Western Marsh Harrier (Bogward Rd, 22nd Aug)

\*Curlew Sandpiper (Balgove Bay, 28th Aug)

\*Lesser Whitethroat (Lade Braes, 3rd Sep)

\*Roseate Tern (Out Head, 4th Sep)

Spotted Flycatcher (Market Street, 6th Sep)

\*Curlew Sandpiper (Balgove Bay, 11th Sep)

\*Curlew Sandpiper (Out Head, 18th Sep)

\*Hawfinch (Bogward Rd, 20th Oct)

\*Brambling (Bogward Rd, 20th Oct)

\*Eurasian Goshawk (Bogward Rd, 20th Oct)

Snow Bunting (Out Head, 26th Oct)

\*Hawfinch (Bogward Rd, 28th Oct)

\*Red Crossbill (Bogward Rd, 28th Oct)

\*Brambling (Bogward Rd, 28th Oct)

\*Eurasian Goshawk (Bogward Rd, 28th Oct)

\*Red Crossbill (Spinkie Den, 3rd Nov)

\*Brambling (Spinkie Den, 3rd Nov)

Arctic Loon (Out Head, 5th Nov)

\*Hawfinch (Bogward Rd, 21st Nov)

\*Arctic Loon (St Andrews Aquarium, 13th Dec)
